import Head from 'next/head';
import Card from '../components/Card';
import CardActions from '../components/CardActions';
import ButtonLink from '../components/ButtonLink';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='stylesheet' href='https://rsms.me/inter/inter.css' />
      </Head>

      <main className='flex max-w-7xl flex-1 flex-col items-center py-4 px-4'>
        <div className='py-10 pt-60 text-center'>
          <h1 className='text-6xl font-bold leading-snug text-sky-600 dark:text-sky-300'>
            Open Seattle
          </h1>
          <h2 className='text-lg'>Technical folks using our powers for good</h2>
        </div>
        <div className='grid gap-4 md:grid-cols-3'>
          <Card>
            <h2 className='text-2xl'>Volunteer</h2>
            <p>
              The problems facing Washington may seem daunting, but luckily
              there&apos;s no shortage of generous, talented Seattlites!
            </p>
            <p className='text-sm italic'>
              Willing to be a regular contributor to a project helping your
              community? Apply to become an Open Seattle Volunteer.
            </p>
            <CardActions>
              <ButtonLink href='https://google.com'>Apply now</ButtonLink>
            </CardActions>
          </Card>

          <Card>
            <h2 className='text-2xl'>Partner</h2>
            <p>
              Communities and local governments know which initiatives would
              have the biggest impact, but frequently lack the people and the
              budget to execute.
            </p>
            <p className='text-sm italic'>
              Have a vision for the community you serve but need some help in
              execution? Apply to become an Open Seattle Partner.
            </p>
            <CardActions>
              <ButtonLink href='https://google.com'>Apply now</ButtonLink>
            </CardActions>
          </Card>

          <Card>
            <h2 className='text-2xl'>Press Inquiries</h2>
            <p>Have a question about Open Seattle?</p>
            <CardActions>
              <ButtonLink href='https://google.com'>Contact us</ButtonLink>
            </CardActions>
          </Card>
        </div>
        <div className='py-10 text-center'>
          <h1 className='text-5xl font-bold leading-snug text-sky-600 dark:text-sky-300'>
            Open Source
          </h1>
          <p className='max-w-prose text-lg'>
            Open Seattle makes it easier for partners, volunteers, and local
            governments to collaborate on open source technology.
          </p>
        </div>
        {/* <div className='flex w-full flex-col items-center justify-between'> */}
        <ul className='flex flex-col gap-4 text-center'>
          <li className='whitespace-nowrap rounded-md bg-slate-300 px-8 py-2 text-2xl dark:bg-white dark:bg-opacity-10'>
            Built for communities
          </li>
          <li className='whitespace-nowrap rounded-md bg-slate-300 px-4 py-2 text-2xl dark:bg-white dark:bg-opacity-10'>
            Free for all to use
          </li>
          <li className='whitespace-nowrap rounded-md bg-slate-300 px-4 py-2 text-2xl dark:bg-white dark:bg-opacity-10'>
            Free to modify
          </li>
        </ul>
        {/* </div> */}
      </main>
    </>
  );
}
