import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Button from '../components/Button';
import Card from '../components/Card';
import CardActions from '../components/CardActions';
import ButtonLink from '../components/ButtonLink';

export default function Home() {
  return (
    <div className='flex min-h-screen flex-col'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className='px-4 py-2'>
        <h1 className='text-lg font-bold leading-tight text-sky-400'>
          Open Seattle
        </h1>
        <p className='text-sm italic leading-tight'>
          Technical folks using our powers for good
        </p>
      </header>

      <main className='flex flex-1 flex-col items-center justify-center py-4 px-4'>
        <div className='grid gap-4 md:grid-cols-3'>
          <Card>
            <h2 className='text-2xl'>Volunteer</h2>
            <p>
              The problems facing Washington may seem daunting, but luckily
              there's no shortage of generous, talented Seattlites!
            </p>
            <p className='text-sm italic'>
              Willing to be a regular contributor to a project helping your
              community? Apply to become an Open Seattle Volunteer.
            </p>
            <CardActions>
              <ButtonLink href='https://google.com'>Apply now</ButtonLink>
            </CardActions>
          </Card>

          <Card>
            <h2 className='text-2xl'>Partner</h2>
            <p>
              Communities and local governments know which initiatives would
              have the biggest impact, but frequently lack the people and the
              budget to execute.
            </p>
            <p className='text-sm italic'>
              Have a vision for the community you serve but need some help in
              execution? Apply to become an Open Seattle Partner.
            </p>
            <CardActions>
              <ButtonLink href='https://google.com'>Apply now</ButtonLink>
            </CardActions>
          </Card>

          <Card>
            <h2 className='text-2xl'>Press Inquiries</h2>
            <p>Have a question about Open Seattle?</p>
            <CardActions>
              <ButtonLink href='https://google.com'>Contact us</ButtonLink>
            </CardActions>
          </Card>
        </div>
      </main>

      <footer className='flex flex-col items-center border-t border-solid border-t-slate-600 py-2'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          <Image
            src='/openseattle-500x392.png'
            alt='Open Seattle Logo'
            width={80}
            height={80}
          />
        </a>
      </footer>
    </div>
  );
}
